/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacio;

/**
 *
 * @author Juanjo
 */
public class Comparar extends javax.swing.JPanel {

    /**
     * Creates new form Comparar
     */
    public Comparar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lSelectFitxer = new java.awt.Label();
        tfPath = new javax.swing.JTextField();
        bBrowser = new javax.swing.JButton();
        bComparar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        bLZW = new javax.swing.JRadioButton();
        bLZSS = new javax.swing.JRadioButton();
        bLZ78 = new javax.swing.JRadioButton();
        bJPEG = new javax.swing.JRadioButton();
        bAuto = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        labelTextNorm = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        labelTextDesc = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();

        setLayout(new java.awt.GridBagLayout());

        lSelectFitxer.setMaximumSize(new java.awt.Dimension(32767, 30));
        lSelectFitxer.setText("Selecciona un fitxer:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 30, 0, 30);
        add(lSelectFitxer, gridBagConstraints);

        tfPath.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        tfPath.setMinimumSize(new java.awt.Dimension(50, 30));
        tfPath.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 30, 0, 30);
        add(tfPath, gridBagConstraints);

        bBrowser.setText("Browser");
        bBrowser.setMaximumSize(new java.awt.Dimension(120, 50));
        bBrowser.setMinimumSize(new java.awt.Dimension(120, 50));
        bBrowser.setPreferredSize(new java.awt.Dimension(120, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 30, 0, 30);
        add(bBrowser, gridBagConstraints);

        bComparar.setText("Comparar");
        bComparar.setMaximumSize(new java.awt.Dimension(120, 50));
        bComparar.setMinimumSize(new java.awt.Dimension(120, 50));
        bComparar.setPreferredSize(new java.awt.Dimension(120, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 20, 30);
        add(bComparar, gridBagConstraints);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 50, 5));

        bLZW.setText("LZW");
        jPanel1.add(bLZW);

        bLZSS.setText("LZSS");
        jPanel1.add(bLZSS);

        bLZ78.setText("LZ78");
        jPanel1.add(bLZ78);

        bJPEG.setText("JEPG");
        jPanel1.add(bJPEG);

        bAuto.setText("Automàtic");
        bAuto.setActionCommand("AUTO");
        jPanel1.add(bAuto);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 20, 30);
        add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        labelTextNorm.setText("Text Normal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 100);
        jPanel2.add(labelTextNorm, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(100, 300));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(108, 500));

        jEditorPane1.setMinimumSize(new java.awt.Dimension(106, 100));
        jEditorPane1.setPreferredSize(new java.awt.Dimension(106, 100));
        jScrollPane1.setViewportView(jEditorPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = -81;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 100);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        labelTextDesc.setText("Text Descomprimit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel2.add(labelTextDesc, gridBagConstraints);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(100, 300));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(108, 500));
        jScrollPane2.setViewportView(jEditorPane2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = -81;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jScrollPane2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bAuto;
    private javax.swing.JButton bBrowser;
    private javax.swing.JButton bComparar;
    private javax.swing.JRadioButton bJPEG;
    private javax.swing.JRadioButton bLZ78;
    private javax.swing.JRadioButton bLZSS;
    private javax.swing.JRadioButton bLZW;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label lSelectFitxer;
    private javax.swing.JLabel labelTextDesc;
    private javax.swing.JLabel labelTextNorm;
    private javax.swing.JTextField tfPath;
    // End of variables declaration//GEN-END:variables
}
