/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacio;

import CapaDomini.Controladors.ControladorEstadisticas;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juanjo
 */
public class Estadistiques extends javax.swing.JPanel {

    ControladorEstadisticas ctrEstadistiques;
    public Estadistiques() throws Exception {
        initComponents();
        addRows();
    }

    
    private void addRows() throws Exception{
        String[][] resultat;
        int sizeX, sizeY;
        
        
        ctrEstadistiques = new ControladorEstadisticas();
        resultat = ctrEstadistiques.executar();
        sizeX = resultat.length;
        DefaultTableModel model = (DefaultTableModel) tableEstadisticas.getModel();
        for(int i=0; i<sizeX; i++){
            model.addRow(resultat[i]);
        }
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tableEstadisticas = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(1000, 700));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setLayout(new java.awt.GridBagLayout());

        tableEstadisticas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableEstadisticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Velocitat", "Percentatge", "Temps"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEstadisticas.setFocusable(false);
        tableEstadisticas.setMinimumSize(new java.awt.Dimension(800, 550));
        tableEstadisticas.setPreferredSize(new java.awt.Dimension(800, 550));
        tableEstadisticas.setRequestFocusEnabled(false);
        tableEstadisticas.setRowHeight(50);
        tableEstadisticas.setRowMargin(10);
        tableEstadisticas.setRowSelectionAllowed(false);
        tableEstadisticas.getTableHeader().setResizingAllowed(false);
        tableEstadisticas.getTableHeader().setReorderingAllowed(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(tableEstadisticas, gridBagConstraints);
        if (tableEstadisticas.getColumnModel().getColumnCount() > 0) {
            tableEstadisticas.getColumnModel().getColumn(0).setResizable(false);
            tableEstadisticas.getColumnModel().getColumn(1).setResizable(false);
            tableEstadisticas.getColumnModel().getColumn(2).setResizable(false);
            tableEstadisticas.getColumnModel().getColumn(3).setResizable(false);
        }
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable tableEstadisticas;
    // End of variables declaration//GEN-END:variables
}
