/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacio;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author bubu0
 */
public class jComprimir extends javax.swing.JFrame {

    private jInici inici;
    private jDescomprimir descomprimir;
    private jComparar comparar;
    
    public jComprimir() {
        initComponents();
        this.setLocationRelativeTo(null);
        pEstadisticas.setVisible(false);
        bLZ78.setActionCommand("LZ78");
        bLZSS.setActionCommand("LZSS");
        bLZW.setActionCommand("LZW");
        bJPEG.setActionCommand("JPEG");
        bAuto.setActionCommand("auto");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bgAlgoritmos = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lSelectFitxer = new java.awt.Label();
        tfPath = new javax.swing.JTextField();
        bBrowse = new javax.swing.JButton();
        bLZW = new javax.swing.JRadioButton();
        bLZ78 = new javax.swing.JRadioButton();
        bLZSS = new javax.swing.JRadioButton();
        bJPEG = new javax.swing.JRadioButton();
        bAuto = new javax.swing.JRadioButton();
        pEstadisticas = new javax.swing.JPanel();
        bComprimir = new javax.swing.JButton();
        mMenu = new javax.swing.JMenuBar();
        jMenuInici = new javax.swing.JMenu();
        jMenuDescomprimir = new javax.swing.JMenu();
        jMenuComparar = new javax.swing.JMenu();

        jDialog1.getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Vols guardar el fitxer comprimit al teu ordinador?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(78, 98, 0, 103);
        jDialog1.getContentPane().add(jLabel1, gridBagConstraints);

        jButton1.setLabel("Sí");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 152, 65, 0);
        jDialog1.getContentPane().add(jButton1, gridBagConstraints);

        jButton2.setLabel("No");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 31, 65, 0);
        jDialog1.getContentPane().add(jButton2, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comprimir");

        lSelectFitxer.setText("Selecciona un fitxer:");

        bBrowse.setText("Browse");
        bBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBrowseActionPerformed(evt);
            }
        });

        bgAlgoritmos.add(bLZW);
        bLZW.setText("LZW");

        bgAlgoritmos.add(bLZ78);
        bLZ78.setText("LZ78");

        bgAlgoritmos.add(bLZSS);
        bLZSS.setText("LZSS");

        bgAlgoritmos.add(bJPEG);
        bJPEG.setText("JEPG");

        bgAlgoritmos.add(bAuto);
        bAuto.setText("Automàtic");

        pEstadisticas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pEstadisticasLayout = new javax.swing.GroupLayout(pEstadisticas);
        pEstadisticas.setLayout(pEstadisticasLayout);
        pEstadisticasLayout.setHorizontalGroup(
            pEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pEstadisticasLayout.setVerticalGroup(
            pEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        bComprimir.setText("Comprimir");
        bComprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComprimirActionPerformed(evt);
            }
        });

        jMenuInici.setText("Inici");
        jMenuInici.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuIniciMouseClicked(evt);
            }
        });
        mMenu.add(jMenuInici);

        jMenuDescomprimir.setText("Descomprimir");
        jMenuDescomprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuDescomprimirMouseClicked(evt);
            }
        });
        mMenu.add(jMenuDescomprimir);

        jMenuComparar.setText("Comparar");
        jMenuComparar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCompararMouseClicked(evt);
            }
        });
        mMenu.add(jMenuComparar);

        setJMenuBar(mMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lSelectFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bLZW)
                                .addGap(33, 33, 33)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfPath)
                                .addGap(18, 18, 18)
                                .addComponent(bBrowse))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bLZ78)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(bLZSS)
                                .addGap(37, 37, 37)
                                .addComponent(bJPEG)
                                .addGap(28, 28, 28)
                                .addComponent(bAuto)
                                .addGap(35, 35, 35)
                                .addComponent(bComprimir)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bBrowse))
                    .addComponent(lSelectFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLZW)
                    .addComponent(bLZ78)
                    .addComponent(bLZSS)
                    .addComponent(bJPEG)
                    .addComponent(bAuto)
                    .addComponent(bComprimir))
                .addGap(14, 14, 14)
                .addComponent(pEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuIniciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuIniciMouseClicked
        inici = new jInici();
        inici.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuIniciMouseClicked

    private void jMenuDescomprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuDescomprimirMouseClicked
        descomprimir = new jDescomprimir();
        descomprimir.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuDescomprimirMouseClicked

    private void jMenuCompararMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCompararMouseClicked
        comparar = new jComparar();
        comparar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCompararMouseClicked

    private void bComprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComprimirActionPerformed
        
        if(bgAlgoritmos.getSelection()==null){
            JOptionPane.showMessageDialog(this, "Selecciona un botó");
            return;
        }else{
            bgAlgoritmos.getSelection().getActionCommand(); //Esta String se la pasamos al controlador para que seleccione el algoritmo de compresion
        }
        
        int guardar = JOptionPane.showConfirmDialog(this,"Vols guardar el fitxer", "Guardar", JOptionPane.YES_NO_OPTION);
        
        if (guardar==0){
            JOptionPane.showMessageDialog(this, "Ha dicho si");
        }else{
            JOptionPane.showMessageDialog(this, "Ha dicho no");
        }
    }//GEN-LAST:event_bComprimirActionPerformed

    private void bBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBrowseActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "txt & ppm", "txt", "ppm");
        chooser.setFileFilter(filter);
        chooser.setAcceptAllFileFilterUsed(false);
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
           tfPath.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_bBrowseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jComprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jComprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jComprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jComprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jComprimir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bAuto;
    private javax.swing.JButton bBrowse;
    private javax.swing.JButton bComprimir;
    private javax.swing.JRadioButton bJPEG;
    private javax.swing.JRadioButton bLZ78;
    private javax.swing.JRadioButton bLZSS;
    private javax.swing.JRadioButton bLZW;
    private javax.swing.ButtonGroup bgAlgoritmos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuComparar;
    private javax.swing.JMenu jMenuDescomprimir;
    private javax.swing.JMenu jMenuInici;
    private java.awt.Label lSelectFitxer;
    private javax.swing.JMenuBar mMenu;
    private javax.swing.JPanel pEstadisticas;
    private javax.swing.JTextField tfPath;
    // End of variables declaration//GEN-END:variables
}
