/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacio;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author bubu0
 */
public class jDescomprimir extends javax.swing.JFrame {

    private jInici inici;
    private jComparar comparar;
    private jComprimir comprimir;
    /**
     * Creates new form jDescomprimir
     */
    public jDescomprimir() {
        initComponents();
        this.setLocationRelativeTo(null);
        pEstadisticas.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        lPregunta = new javax.swing.JLabel();
        bSi = new javax.swing.JButton();
        bNo = new javax.swing.JButton();
        lSelectFitxer = new java.awt.Label();
        tfPath = new javax.swing.JTextField();
        pEstadisticas = new javax.swing.JPanel();
        bBrowse = new javax.swing.JButton();
        bDescomprimir = new javax.swing.JButton();
        mMenu = new javax.swing.JMenuBar();
        jMenuInici = new javax.swing.JMenu();
        jMenuComprimir = new javax.swing.JMenu();
        jMenuComparar = new javax.swing.JMenu();

        lPregunta.setText("Vols guardar el fitxer comprimit al teu ordinador?");

        bSi.setLabel("Sí");

        bNo.setLabel("No");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog1Layout.createSequentialGroup()
                    .addGap(0, 81, Short.MAX_VALUE)
                    .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lPregunta)
                        .addGroup(jDialog1Layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(bSi)
                            .addGap(31, 31, 31)
                            .addComponent(bNo)))
                    .addGap(0, 82, Short.MAX_VALUE)))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog1Layout.createSequentialGroup()
                    .addGap(0, 43, Short.MAX_VALUE)
                    .addComponent(lPregunta)
                    .addGap(18, 18, 18)
                    .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bSi)
                        .addComponent(bNo))
                    .addGap(0, 44, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Descomprimir");

        lSelectFitxer.setText("Selecciona un fitxer:");

        pEstadisticas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pEstadisticas.setToolTipText("");

        javax.swing.GroupLayout pEstadisticasLayout = new javax.swing.GroupLayout(pEstadisticas);
        pEstadisticas.setLayout(pEstadisticasLayout);
        pEstadisticasLayout.setHorizontalGroup(
            pEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pEstadisticasLayout.setVerticalGroup(
            pEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        bBrowse.setText("Browse");
        bBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBrowseActionPerformed(evt);
            }
        });

        bDescomprimir.setText("Descomprimir");
        bDescomprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDescomprimirActionPerformed(evt);
            }
        });

        jMenuInici.setText("Inici");
        jMenuInici.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuIniciMouseClicked(evt);
            }
        });
        mMenu.add(jMenuInici);

        jMenuComprimir.setText("Comprimir");
        jMenuComprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuComprimirMouseClicked(evt);
            }
        });
        mMenu.add(jMenuComprimir);

        jMenuComparar.setText("Comparar");
        jMenuComparar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCompararMouseClicked(evt);
            }
        });
        mMenu.add(jMenuComparar);

        setJMenuBar(mMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lSelectFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPath, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(bBrowse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bDescomprimir)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bBrowse)
                        .addComponent(bDescomprimir))
                    .addComponent(lSelectFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bDescomprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDescomprimirActionPerformed
        int guardar = JOptionPane.showConfirmDialog(this,"Vols guardar el fitxer descomprimit", "Guardar", JOptionPane.YES_NO_OPTION);
        
        if (guardar==0){
            JOptionPane.showMessageDialog(this, "Ha dicho si");
        }else{
            JOptionPane.showMessageDialog(this, "Ha dicho no");
        }
    }//GEN-LAST:event_bDescomprimirActionPerformed

    private void jMenuIniciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuIniciMouseClicked
        inici = new jInici();
        inici.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuIniciMouseClicked

    private void jMenuComprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuComprimirMouseClicked
        comprimir = new jComprimir();
        comprimir.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuComprimirMouseClicked

    private void jMenuCompararMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCompararMouseClicked
        comparar = new jComparar();
        comparar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCompararMouseClicked

    private void bBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBrowseActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "LZSS, LZW, LZ78, JPEGCOMP & CARPCOMP", "lzss", "lz78","lzw","jpegComp");
        chooser.setFileFilter(filter);
        chooser.setAcceptAllFileFilterUsed(false);
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
           tfPath.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_bBrowseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDescomprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDescomprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDescomprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDescomprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jDescomprimir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBrowse;
    private javax.swing.JButton bDescomprimir;
    private javax.swing.JButton bNo;
    private javax.swing.JButton bSi;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenu jMenuComparar;
    private javax.swing.JMenu jMenuComprimir;
    private javax.swing.JMenu jMenuInici;
    private javax.swing.JLabel lPregunta;
    private java.awt.Label lSelectFitxer;
    private javax.swing.JMenuBar mMenu;
    private javax.swing.JPanel pEstadisticas;
    private javax.swing.JTextField tfPath;
    // End of variables declaration//GEN-END:variables
}
