/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacio;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JFrame;

/**
 *
 * @author bubu0
 */
public class jInici extends javax.swing.JFrame {

    private jComprimir comprimir;
    private jComparar comparar;
    private jDescomprimir descomprimir;
    
    public jInici() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bComprimir = new javax.swing.JButton();
        bComparar = new javax.swing.JButton();
        bSortir = new javax.swing.JButton();
        bDescomprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROP");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("jInici"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        bComprimir.setText("Comprimir");
        bComprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bComprimir.setMaximumSize(new java.awt.Dimension(250, 60));
        bComprimir.setMinimumSize(new java.awt.Dimension(110, 25));
        bComprimir.setPreferredSize(new java.awt.Dimension(110, 25));
        bComprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComprimirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        gridBagConstraints.insets = new java.awt.Insets(41, 152, 0, 151);
        getContentPane().add(bComprimir, gridBagConstraints);

        bComparar.setText("Comparar");
        bComparar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bComparar.setMaximumSize(new java.awt.Dimension(250, 60));
        bComparar.setMinimumSize(new java.awt.Dimension(110, 25));
        bComparar.setPreferredSize(new java.awt.Dimension(110, 25));
        bComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCompararActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 152, 0, 151);
        getContentPane().add(bComparar, gridBagConstraints);

        bSortir.setText("Sortir");
        bSortir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSortir.setMaximumSize(new java.awt.Dimension(250, 60));
        bSortir.setMinimumSize(new java.awt.Dimension(110, 25));
        bSortir.setPreferredSize(new java.awt.Dimension(110, 25));
        bSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSortirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 152, 42, 151);
        getContentPane().add(bSortir, gridBagConstraints);

        bDescomprimir.setText("Descomprimir");
        bDescomprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bDescomprimir.setMaximumSize(new java.awt.Dimension(250, 60));
        bDescomprimir.setMinimumSize(new java.awt.Dimension(110, 25));
        bDescomprimir.setPreferredSize(new java.awt.Dimension(110, 25));
        bDescomprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDescomprimirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 152, 0, 151);
        getContentPane().add(bDescomprimir, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bComprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComprimirActionPerformed
        comprimir = new jComprimir();
        comprimir.setVisible(true);
        dispose();
    }//GEN-LAST:event_bComprimirActionPerformed

    private void bDescomprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDescomprimirActionPerformed
        descomprimir = new jDescomprimir();
        descomprimir.setVisible(true);
        dispose();
    }//GEN-LAST:event_bDescomprimirActionPerformed

    private void bCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCompararActionPerformed
        comparar = new jComparar();
        comparar.setVisible(true);
        dispose();
    }//GEN-LAST:event_bCompararActionPerformed

    private void bSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSortirActionPerformed
        dispose();
    }//GEN-LAST:event_bSortirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jInici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jInici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jInici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jInici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jInici().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bComparar;
    private javax.swing.JButton bComprimir;
    private javax.swing.JButton bDescomprimir;
    private javax.swing.JButton bSortir;
    // End of variables declaration//GEN-END:variables
}
